### PR TITLE
Remove level-specific hooks

### PR DESCRIPTION
**Pull request by Kalobi**
This pattern can create double hooks because there are ways to exit a level other than the OverworldLoader. Maybe a revised version of this can be readded eventually, but level-specific hooks are pretty niche and a broken version is worse than no version.

### CODE REVIEW

**Comment by swoolcock** [comment]
I mean... this is arguably the correct way to apply hooks, so I'd rather actually fix it than remove it.  Gravity Helper does it this way and I've never encountered double hooks.

**Comment by Kalobi** [comment]
If you console load into a map, OverworldLoader is never involved: https://discord.com/channels/403698615446536203/908809001834274887/1183870143089082511 And loading different combinations of hooks in different levels makes hook incompatibilities much harder to pin down since you might have to wait for a map that happens to use both at the same time. Also IMO increased map loading times are more annoying than startup times, since they break the gameplay flow more.

**Comment by Kalobi** [comment]
GravityHelper seems to be doing some much more complex tracking with the HookLevel stuff.

**Comment by swoolcock** [comment]
Fair enough, yeah Gravity Helper has different levels of hooking that it keeps track of, since maps like paint only require the ability to flip the player visually.

**Pull request merged**
